name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ release ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}

jobs:
  RunCIJob:
    uses: ./.github/workflows/ci.yml

  BuildAndPushDockerImage:
    name: Build image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs: [ RunCIJob ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_TOKEN

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            $DOCKER_REGISTRY/go-cicd:latest
            $DOCKER_REGISTRY/go-cicd:${{ github.sha }}